camera:
  - clip_color: !tuple
      - 0.01
      - 1000.0
    clip_depth: !tuple
      - 0.05
      - 10.0
    enable: true
    height: 1080
    width: 1920
    horizontal_fov: 1.0471975511965976
    image_format: R8G8B8
    name: robot_camera
    noise_mean: null
    noise_stddev: null
    publish_color: true
    publish_depth: false
    publish_points: false
    random_pose_focal_point_z_offset: 0.0
    random_pose_mode: orbit
    random_pose_orbit_distance: 1.0
    random_pose_orbit_height_range: !tuple
      - 0.1
      - 0.7
    random_pose_orbit_ignore_arc_behind_robot: 0.39269908169872414
    random_pose_rollout_counter: 0.0
    random_pose_rollouts_num: 1
    random_pose_select_position_options: []
    relative_to: link_6
    spawn_position: !tuple
      - 0.0
      - -0.03
      - 0.0
    spawn_quat_xyzw: !tuple
      - 0.5
      - -0.5
      - 0.5
      - 0.5
    type: rgbd_camera
    update_rate: 10
    vertical_fov: 1.0471975511965976
gravity: !tuple
  - 0.0
  - 0.0
  - -9.80665
gravity_std: !tuple
  - 0.0
  - 0.0
  - 0.0232
light:
  color: !tuple
    - 1.0
    - 1.0
    - 1.0
    - 1.0
  direction: !tuple
    - 0.5
    - -0.25
    - -0.75
  distance: 1000.0
  model_rollouts_num: 1
  radius: 25.0
  random_minmax_elevation: !tuple
    - -0.15
    - -0.65
  type: sun
  visual: true
objects:
  - color: null
    name: star
    orientation: !tuple
      - 1.0
      - 0.0
      - 0.0
      - 0.0
    position: !tuple
      - 0.1
      - 0.33
      - 0.1
    randomize:
      count: 0
      models_rollouts_num: 0
      random_color: false
      random_model: false
      random_orientation: false
      random_pose: false
      random_position: false
      random_spawn_position_segments: []
      random_spawn_position_update_workspace_centre: false
      random_spawn_volume: !tuple
        - 0.5
        - 0.5
        - 0.5
    relative_to: world
    static: false
    texture: []
    type: "model"

  - color: null
    name: box
    mass: 1.0
    size: !tuple
      - 0.02
      - 0.02
      - 0.05
    orientation: !tuple
      - 1.0
      - 0.0
      - 0.0
      - 0.0
    position: !tuple
      - 0.1
      - 0.30
      - 0.1
    randomize:
      count: 0
      models_rollouts_num: 0
      random_color: false
      random_model: false
      random_orientation: false
      random_pose: false
      random_position: false
      random_spawn_position_segments: []
      random_spawn_position_update_workspace_centre: false
      random_spawn_volume: !tuple
        - 0.5
        - 0.5
        - 0.5
    relative_to: world
    static: false
    type: "box"


  - color: null
    name: cylinder
    mass: 1.0
    radius: 0.01
    length: 0.05
    orientation: !tuple
      - 1.0
      - 0.0
      - 0.0
      - 0.0
    position: !tuple
      - 0.1
      - 0.27
      - 0.1
    randomize:
      count: 0
      models_rollouts_num: 0
      random_color: false
      random_model: false
      random_orientation: false
      random_pose: false
      random_position: false
      random_spawn_position_segments: []
      random_spawn_position_update_workspace_centre: false
      random_spawn_volume: !tuple
        - 0.5
        - 0.5
        - 0.5
    relative_to: world
    static: false
    type: "cylinder"

  - color: null
    name: board
    orientation: !tuple
      - 1.0
      - 0.0
      - 0.0
      - 0.0
    position: !tuple
      - 0.0
      - 0.3
      - 0.01
    randomize:
      count: 0
      models_rollouts_num: 0
      random_color: false
      random_model: false
      random_orientation: false
      random_pose: false
      random_position: false
      random_spawn_position_segments: []
      random_spawn_position_update_workspace_centre: false
      random_spawn_volume: !tuple
        - 0.5
        - 0.5
        - 0.5
    relative_to: world
    static: true
    texture: []
    type: "model"
physics_rollouts_num: 0
plugins:
  fts_broadcaster: false
  scene_broadcaster: false
  sensors_render_engine: ogre2
  user_commands: false
robot:
  gripper_joint_positions: 0.0
  joint_positions:
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
  name: ar4
  randomizer:
    joint_positions: false
    joint_positions_above_object_spawn: false
    joint_positions_above_object_spawn_elevation: 0.2
    joint_positions_above_object_spawn_xy_randomness: 0.2
    joint_positions_std: 0.1
    pose: false
    spawn_volume: !tuple
      - 1.0
      - 1.0
      - 0.0
  spawn_position: !tuple
    - 0.0
    - 0.0
    - 0.0
  spawn_quat_xyzw: !tuple
    - 0.0
    - 0.0
    - 1.0
    - 0.0
  urdf_string: ""
  with_gripper: true
terrain:
  model_rollouts_num: 1
  name: ground
  size: !tuple
    - 1.5
    - 1.5
  spawn_position: !tuple
    - 0
    - 0
    - 0
  spawn_quat_xyzw: !tuple
    - 0
    - 0
    - 0
    - 1
  type: flat
  ambient: !tuple
    - 0.2
    - 0.2
    - 0.2
    - 1.0
  diffuse: !tuple
    - 0.2
    - 0.2
    - 0.2
    - 1.0
  specular: !tuple
    - 0.1
    - 0.1
    - 0.1
    - 1.0
